language: node_js
node_js:
  - "8"
sudo: required
addons:
    chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm set progress=false
  - npm install
script:
  - ng lint
  - npm run test --code-coverage
  - npm run e2e
  - npm run build
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
